## Database Config.
database:
  database: Burton
  host: localhost
  port: 3306
  username: root
  password: 1234
  # MySQLAdapter <-  DBs available
  type: MySQLAdapter
api:
  url: https://api.escuelajs.co/api/v1/